
default_language_version:
  python: python3.11
# fail_fast: true # stop on first error
repos:
  - repo: https://github.com/pdm-project/pdm
    rev: 2.10.3 # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check
